ydisk/actions/urls.py
"""Схемы URL для actions"""

from django.urls import path

from .views import PublicKeyView, UserLoginView, clear_link, logout_user

app_name = 'actions'

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('public-key/', PublicKeyView.as_view(), name='public_key'),
    path('public-key/<path:public_key>/<str:path>/', PublicKeyView.as_view(), name='public_key'),
    path('clear-link/', clear_link, name='clear_link'),
    path('logout/', logout_user, name='logout'),
]

ydisk/ydisk/urls.py
from django.contrib import admin
from django.urls import include, path

from actions.views import pageNotFound

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('actions.urls', namespace='actions')),
]

if settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns

handler403 = pageNotFound
handler404 = pageNotFound

ydisk/actions/models.py
from django.db import models

# Create your models here.

ydisk/actions/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class UserLoginForm(AuthenticationForm):
    """ Форма авторизация пользователя """

    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Username'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Password'}))

    class Meta:
        fields = ('username', 'password')


class LinkForm(forms.Form):
    """ Форма ввода публичной ссылки для просмотра файлов """

    public_key = forms.URLField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'input_public_key', 'placeholder': 'введите публичную ссылку'}),
        label='public_key',
    )

    class Meta:
        fields = ('public_key',)

ydisk/actions/views.py
import yadisk
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.core.cache import cache
from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from common.views import YandexClient

from .forms import LinkForm, UserLoginForm


class UserLoginView(LoginView):
    """ Представление домашней страницы для авторизации пользователя """

    form_class = UserLoginForm
    template_name = 'actions/login.html'
    title = 'Авторизация'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class PublicKeyView(LoginRequiredMixin, View, YandexClient):
    """ Представление работы с публичной ссылкой """

    title = 'Публичная ссылка'
    form_class = LinkForm

    def get(self, request, public_key: str = None, path: str = None):
        context = {
            'form': self.form_class(),
            'title': self.title,
        }

        if path:
            data_from_cache = cache.get('/'.join([public_key, path]))
            if data_from_cache:
                public_resources, public_resources_path = data_from_cache
            else:
                try:
                    public_resources, public_resources_path = self.get_public_resources(
                        public_key=public_key,
                        path=path
                    )
                    cache.set('/'.join([public_key, path]), (public_resources, public_resources_path), 3600)
                except yadisk.exceptions.NotFoundError:
                    return redirect(reverse('actions:public_key'))

            context.update({
                'form': self.form_class({'public_key': public_key}),
                'public_resources_path': public_resources_path,
                'public_resources': public_resources,
                'public_key': public_key
            })

        return render(request, 'actions/public_key.html', context=context)

    def post(self, request, public_key: str = None, path: str = '/'):
        public_key = request.POST.get('public_key')

        if request.POST.get('enter_public_key'):
            reverse_url = reverse('actions:public_key', kwargs={'public_key': public_key, 'path': '*'})
            return redirect(reverse_url)

        if request.POST.get('level_up'):
            pre_path = path.rpartition('*')[0]  # при перемещении на уровень вверх убираем заднюю часть из пути
            path = pre_path if pre_path else '*'  # если верхн. уровень, то '*', заменится на '/' в get_public_resources
            reverse_url = reverse('actions:public_key', kwargs={'public_key': public_key, 'path': path})
            return redirect(reverse_url)

        if request.POST.get('download_selected'):
            selected_resources = [v for k, v in request.POST.items() if k.isdigit()]
            self.download_files(public_key=public_key, path=path, selected_resources=selected_resources)

        if request.POST.get('download_all'):
            self.download_all(public_key=public_key, path=path)

        public_resources, public_resources_path = self.get_public_resources(public_key=public_key, path=path)

        context = {
            'form': self.form_class(request.POST),
            'title': self.title,
            'public_resources_path': public_resources_path,
            'public_resources': public_resources,
            'public_key': public_key
        }

        return render(request, 'actions/public_key.html', context=context)


def clear_link(request):
    """ Функция очистки поля формы публичной ссылки """
    redirect_url = reverse('actions:public_key')
    return redirect(redirect_url)


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


def logout_user(request):
    logout(request)
    return redirect('/')

ydisk/actions/templates/actions/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{% block title %} {% endblock title %}</title>

        <!-- Base CSS -->
        <link rel="stylesheet" href="{% static 'actions/css/base.css' %}" xmlns="http://www.w3.org/1999/html">
        {% block css %} {% endblock %}

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'actions/icons/favicons/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'actions/icons/favicons//favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'actions/icons/favicons//favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'actions/icons/favicons/site.webmanifest' %}">
    </head>

    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

        <!-- Header -->
        <header class="header">
            <div class="header__container">
                <div class="header__container-logo">
                    <img class="header__logo" src="{% static 'actions/icons/logo_folder.png' %}" alt="logo">
                </div>
                {% if user.is_authenticated %}
                <div class="header__container-logout">
                    <a href="{% url 'actions:logout' %}">
                        <img class="header__logout" src="{% static 'actions/icons/logout.png' %}" alt="logo">
                    </a>
                </div>
                {% endif %}
            </div>
        </header>

        <!-- Контент страницы -->
        {% block content %} {% endblock %}
        <script src="https://unpkg.com/htmx.org@1.9.4"></script>
    </body>

    {% block script %} {% endblock script %}
</html>

ydisk/actions/templates/actions/login.html
{% extends 'actions/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'actions/css/base.css' %}" xmlns="http://www.w3.org/1999/html">
<link rel="stylesheet" href="{% static 'actions/css/login.css' %}" xmlns="http://www.w3.org/1999/html">
{% endblock %}

{% block title %} {{title}} {% endblock %}

{% block content %}

<div class="login">
    <h1></h1>
<form method="post">
    {% csrf_token %}
    {{form.username}}
    {{form.password}}
    <button type="submit" class="btn btn-primary btn-block btn-large">Log in</button>
</form>
</div>

{% endblock %}

ydisk/actions/templates/actions/main.html
{% extends 'actions/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'actions/css/main.css' %}" xmlns="http://www.w3.org/1999/html">
{% endblock %}

{% block title %} {{title}} {% endblock %}

{% block content %}

<div class="city">
    <h1></h1>
    <form method="post">
        {% csrf_token %}

        <div class="form__clear">
        {{form.city}}
        <a href="{% url 'actions:clear_search' %}"><button type="button" class="btn btn-primary btn-x">X</button></a>
        </div>

        <button type="submit" class="btn btn-primary btn-block btn-large">Получить прогноз</button>
    </form>
    <div class="forecast">
        {% for dt in date_and_temperature_list %}
            <div class="forecast__days">{{dt.date|date:"d"}} {{dt.date|date:"D"}}
                        <br>{{dt.temperature|default:"-"}}&#8451
            </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

{% block script %}
    {% if error %}
        <script>
            setTimeout(() => {  alert("К сожалению указанный город не удалось определить"); }, 200);
        </script>
    {% endif %}
{% endblock script %}

ydisk/actions/templates/actions/public_key.html
{% extends 'actions/base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'actions/css/public_link.css' %}" xmlns="http://www.w3.org/1999/html">
{% endblock %}

{% block title %} {{title}} {% endblock %}

{% block content %}

<div class="public_link">
    <form method="post">
        {% csrf_token %}

        <div class="form__public_key">
        {{form.public_key}}
        <a href="{% url 'actions:clear_link' %}"><button type="button" class="btn btn-primary btn-x">X</button></a>
        <button class="btn btn-primary btn-block btn-large" name="enter_public_key" value="True" type="submit">Enter</button>
        </div>

            <div class="public_link__data public_resources">
                {% if public_resources_path %}
                <div class="public_resources__path">
                    <div class="public_resources__path_str">{{public_resources_path}}</div>
                    <button class="btn btn-level-up" name="level_up" value="True" type="submit">&#8593</button>
                </div>
                {% endif %}
                {% if public_resources %}
                    <table class="public_resources__table resource" style="width:100%">
                        {% for pr in public_resources %}
                        <tr>
                            <td class="resource__input">
                                <input type="checkbox" name="{{forloop.counter}}" value="{{pr.name}}">
                            </td>
                            {% if pr.type == 'dir' %}
                                <td class="resource__type">&#128193;</td>
                                <td><label for="id_resource"><a href="{% url 'actions:public_key' public_key pr.path %}">{{pr.name}}</a></label></td>
                            {% else %}
                                <td class="resource__type">&#128196;</td>
                                <td><label for="id_resource">{{pr.name}}</label></td>
                            {% endif %}
                            
                        </tr>
                        {% endfor %}
                    </table>
                <div class="public_resources__downloads">
                    <button class="btn btn-primary btn-block btn-downloads" name="download_selected" value="True" type="submit">Скачать выбранные файлы</button>
                    <button class="btn btn-primary btn-block btn-downloads" name="download_all" value="True" type="submit">Скачать всё одним архивом</button>
                </div>
                {% endif %}
            </div>
    </form>
</div>

{% endblock %}

{% block script %}
{% endblock script %}

ydisk/actions/templates/actions/public_link.html
{% extends 'actions/base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'actions/css/public_link.css' %}" xmlns="http://www.w3.org/1999/html">
{% endblock %}

{% block title %} {{title}} {% endblock %}

{% block content %}

<div class="public_link">
    <form method="post">
        {% csrf_token %}

        <div class="form__public_key">
        {{form.public_key}}
        <a href="{% url 'actions:clear_link' %}"><button type="button" class="btn btn-primary btn-x">X</button></a>
        <button class="btn btn-primary btn-block btn-large" name="enter_public_key" value="True" type="submit">Enter</button>
        </div>

            <div class="public_link__data public_resources">
                {% if public_resources_path %}
                <div class="public_resources__path">
                    <div class="public_resources__path_str">{{public_resources_path}}</div>
                    <button class="btn btn-level-up" name="level_up" value="True" type="submit">&#8593</button>
                </div>
                {% endif %}
                {% if public_resources %}
                    <table class="public_resources__table resource" style="width:100%">
                        {% for pr in public_resources %}
                        <tr>
                            <td class="resource__input">
                                <input type="checkbox" name="{{forloop.counter}}" value="{{pr.name}}">
                            </td>
                            {% if pr.type == 'dir' %}
                                <td class="resource__type">&#128193;</td>
                                <td><label for="id_resource"><a href="{% url 'actions:public_key' public_key pr.path %}">{{pr.name}}</a></label></td>
                            {% else %}
                                <td class="resource__type">&#128196;</td>
                                <td><label for="id_resource">{{pr.name}}</label></td>
                            {% endif %}
                            
                        </tr>
                        {% endfor %}
                    </table>
                <div class="public_resources__downloads">
                    <button class="btn btn-primary btn-block btn-downloads" name="download_selected" value="True" type="submit">Скачать выбранные файлы</button>
                    <button class="btn btn-primary btn-block btn-downloads" name="download_all" value="True" type="submit">Скачать одним архивом</button>
                </div>
                {% endif %}
            </div>
    </form>
</div>

{% endblock %}

{% block script %}
{% endblock script %}